#!/bin/bash
-rw-r--r-- 1 root root 66 Feb 8 02:09 0-current_working_directory -rwxr--r-- 1 root root 87 Feb 8 02:46 1-listit -rw-r--r-- 1 root root 21 Feb 8 02:31 2-bring_me_home -rw-r--r-- 1 root root 33 Feb 8 01:35 README.md
